storage_config_generation: 0
static_erasure: mirror-3-dc
host_configs:
- drive:
  - path: /dev/disk/by-partlabel/ydb_disk_1
    type: SSD
  - path: /dev/disk/by-partlabel/ydb_disk_2
    type: SSD
  host_config_id: 1
hosts:
- node_id: 11
  host: ydb-old-1
  host_config_id: 1
  walle_location:
    body: 1
    data_center: 'zone-a'
    rack: '1'
- node_id: 12
  host: ydb-old-2
  host_config_id: 1
  walle_location:
    body: 2
    data_center: 'zone-a'
    rack: '2'
- node_id: 13
  host: ydb-old-3
  host_config_id: 1
  walle_location:
    body: 3
    data_center: 'zone-a'
    rack: '3'
- node_id: 14
  host: ydb-old-4
  host_config_id: 1
  walle_location:
    body: 4
    data_center: 'zone-a'
    rack: '4'
- node_id: 21
  host: ydb-old-5
  host_config_id: 1
  walle_location:
    body: 5
    data_center: 'zone-b'
    rack: '5'
- node_id: 22
  host: ydb-old-6
  host_config_id: 1
  walle_location:
    body: 6
    data_center: 'zone-b'
    rack: '6'
- node_id: 23
  host: ydb-old-7
  host_config_id: 1
  walle_location:
    body: 7
    data_center: 'zone-b'
    rack: '7'
- node_id: 24
  host: ydb-old-8
  host_config_id: 1
  walle_location:
    body: 8
    data_center: 'zone-b'
    rack: '8'
- node_id: 31
  host: ydb-old-9
  host_config_id: 1
  walle_location:
    body: 9
    data_center: 'zone-c'
    rack: '9'
- node_id: 32
  host: ydb-old-10
  host_config_id: 1
  walle_location:
    body: 10
    data_center: 'zone-c'
    rack: '10'
- node_id: 33
  host: ydb-old-11
  host_config_id: 1
  walle_location:
    body: 11
    data_center: 'zone-c'
    rack: '11'
- node_id: 34
  host: ydb-old-12
  host_config_id: 1
  walle_location:
    body: 12
    data_center: 'zone-c'
    rack: '12'

blob_storage_config:
  service_set:
    groups:
    - erasure_species: mirror-3-dc
      rings:
      - fail_domains:
        - vdisk_locations:
          - node_id: 11
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 12
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 13
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
      - fail_domains:
        - vdisk_locations:
          - node_id: 21
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 22
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 23
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
      - fail_domains:
        - vdisk_locations:
          - node_id: 31
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 32
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 33
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1

domains_config:
  domain:
  - name: Domain0
    storage_pool_types:
    - kind: ssd
      pool_config:
        box_id: 1
        erasure_species: mirror-3-dc
        kind: ssd
        pdisk_filter:
        - property:
          - type: SSD
        vdisk_kind: Default
  state_storage:
  - ring:
      node: [11, 12, 13, 21, 22, 23, 31, 32, 33]
      nto_select: 9
    ssid: 1
  security_config:
    enforce_user_token_requirement: true      # User 'root' with the empty password out of box
    monitoring_allowed_sids:
    - "root"
    - "ADMINS"
    - "DATABASE-ADMINS"
    administration_allowed_sids:
    - "root"
    - "ADMINS"
    - "DATABASE-ADMINS"
    viewer_allowed_sids:
    - "root"
    - "ADMINS"
    - "DATABASE-ADMINS"

channel_profile_config:
  profile:
  - channel:
    - erasure_species: mirror-3-dc
      pdisk_category: 1   # 0=ROT, 1=SSD, 2=NVME
      storage_pool_kind: ssd
    - erasure_species: mirror-3-dc
      pdisk_category: 1
      storage_pool_kind: ssd
    - erasure_species: mirror-3-dc
      pdisk_category: 1
      storage_pool_kind: ssd
    profile_id: 0

interconnect_config:
    start_tcp: true
    encryption_mode: OPTIONAL
    path_to_certificate_file: "/opt/ydb/certs/node.crt"
    path_to_private_key_file: "/opt/ydb/certs/node.key"
    path_to_ca_file: "/opt/ydb/certs/ca.crt"

grpc_config:
    cert: "/opt/ydb/certs/node.crt"
    key: "/opt/ydb/certs/node.key"
    ca: "/opt/ydb/certs/ca.crt"
    services_enabled:
    - legacy

bootstrap_config:
  shared_cache_config: {memory_limit: '4294967296'}

log_config:
  default_level: 3

table_service_config:
  sql_version: 1
  index_auto_choose_mode: MAX_USED_PREFIX
  enable_kqp_data_query_stream_lookup: true

column_shard_config:
  disabled_on_scheme_shard: false

feature_flags:
  enable_grpc_audit: false
  enable_get_node_labels: true
  enable_views: true
  enable_external_data_sources: true
  enable_script_execution_operations: true

audit_config:
  file_backend:
    format: JSON
    file_path: "ydb-audit.log"

# *************************
# Actor system config is appended to the configuration file by Ansible task.
# Provided here in the commented form for reference
#actor_system_config:
#  use_auto_config: true
#  node_type: STORAGE # STORAGE or COMPUTE
#  cpu_count: 6
# *************************
